export const runStateData = {
    "code":0,
    "msg":"success",
    "data":[
        {
            "regionName":"江西区域",
            "projectsInfo":[
                {
                    "projectStatus":1,
                    "unitsInfo":[
                        {
                            "unitName":"#2机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#1机组",
                            "unitStatus":1
                        }
                    ],
                    "projectName":"新昌"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#5机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#6机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"贵2"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"贵3"
                },
                {
                    "projectStatus":1,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":1
                        }
                    ],
                    "projectName":"景德镇"
                },
                {
                    "projectStatus":1,
                    "unitsInfo":[
                        {
                            "unitName":"#9机组",
                            "unitStatus":1
                        }
                    ],
                    "projectName":"分宜"
                }
            ]
        },
        {
            "regionName":"东北区域",
            "projectsInfo":[
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"朝阳"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"大连"
                }
            ]
        },
        {
            "regionName":"河南区域",
            "projectsInfo":[
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"南阳"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#6机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#7机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"平东"
                },
                {
                    "projectStatus":1,
                    "unitsInfo":[
                        {
                            "unitName":"#7机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#6机组",
                            "unitStatus":1
                        }
                    ],
                    "projectName":"新乡"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":1
                        }
                    ],
                    "projectName":"良村"
                },
                {
                    "projectStatus":1,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":1
                        }
                    ],
                    "projectName":"开封"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"鲁阳"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#5机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#6机组",
                            "unitStatus":1
                        },
                        {
                            "unitName":"#4机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"中孚"
                },
                {
                    "projectStatus":1,
                    "unitsInfo":[

                    ],
                    "projectName":"沁阳"
                }
            ]
        },
        {
            "regionName":"内蒙公司",
            "projectsInfo":[
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"新丰"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"金山"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"锡林"
                },
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"乌斯太"
                }
            ]
        },
        {
            "regionName":"西南区域",
            "projectsInfo":[
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":0
                        }
                    ],
                    "projectName":"二郎"
                },
                {
                    "projectStatus":1,
                    "unitsInfo":[

                    ],
                    "projectName":"盘县"
                },
                {
                    "projectStatus":1,
                    "unitsInfo":[

                    ],
                    "projectName":"务川"
                }
            ]
        },
        {
            "regionName":"西北区域",
            "projectsInfo":[
                {
                    "projectStatus":0,
                    "unitsInfo":[
                        {
                            "unitName":"#1机组",
                            "unitStatus":0
                        },
                        {
                            "unitName":"#2机组",
                            "unitStatus":1
                        }
                    ],
                    "projectName":"乌苏"
                },
                {
                    "projectStatus":1,
                    "unitsInfo":[

                    ],
                    "projectName":"宁东"
                }
            ]
        }
    ]
}